#!/bin/sh
#ecommerce
echo CI_JOB_TOKEN=$CI_JOB_TOKEN  >> .env
echo CI_REGISTRY_USER=$CI_REGISTRY_USER   >> .env
echo CI_REGISTRY=$CI_REGISTRY  >> .env
echo DEBUG=0 >> .env
echo IMAGE=$IMAGE >> .env
echo NGINX_IMAGE=$IMAGE:nginx  >> .env

echo REACT_APP_API_URL=$REACT_APP_API_URL >> .env
echo REACT_APP_CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA >> .env
echo REACT_APP_CI_COMMIT_TIMESTAMP=$CI_COMMIT_TIMESTAMP >> .env
echo REACT_APP_GHN_API_URL=$REACT_APP_GHN_API_URL  >> .env
echo REACT_APP_GHN_SHOP_ID=$REACT_APP_GHN_SHOP_ID  >> .env
echo REACT_APP_GHN_TOKEN=$REACT_APP_GHN_TOKEN  >> .env
echo REACT_APP_HOTLINE=$REACT_APP_HOTLINE  >> .env
echo REACT_APP_NGINX_IMAGE=$IMAGE:nginx  >> .env
echo REACT_APP_ORGANIZATION_ID=$REACT_APP_ORGANIZATION_ID  >> .env
echo REACT_APP_REPORT_API=$REACT_APP_API_REPORT >> .env
echo REACT_APP_SENTRY_URL=$REACT_APP_SENTRY_URL >> .env
echo REACT_APP_SHOP_ADDRESS=$REACT_APP_SHOP_ADDRESS  >> .env
echo REACT_APP_SHOP_NAME_2=$REACT_APP_SHOP_NAME_2  >> .env
echo REACT_APP_SHOP_NAME=$REACT_APP_SHOP_NAME  >> .env
echo REACT_APP_SKYCOM_API=$REACT_APP_SKYCOM_API >> .env
echo REACT_APP_URL_DATA=$REACT_APP_API_URL_DATA >> .env
echo REACT_APP_API_SYNC_DATA=$REACT_APP_API_SYNC_DATA >> .env
echo REACT_APP_CALL_CENTER_API=$REACT_APP_CALL_CENTER_API  >> .env
