import { PathDashboardType } from "_types_/RouterPathTypes";
import {
  PROMOTION_ROLES,
  ROLE_TAB,
  STATUS_ROLE_AIRTABLE,
  STATUS_ROLE_ATTRIBUTE,
  STATUS_ROLE_CDP,
  STATUS_ROLE_CONTENT_DAILY,
  STATUS_ROLE_CONTENT_ID,
  STATUS_ROLE_DATA_FLOW,
  STATUS_ROLE_ECOMMERCE,
  STATUS_ROLE_FACEBOOK,
  STATUS_ROLE_GOOGLE,
  STATUS_ROLE_LIST_PRODUCT,
  STATUS_ROLE_MANAGE_FILE,
  STATUS_ROLE_PRODUCT,
  STATUS_ROLE_REPORT_REVENUE,
  STATUS_ROLE_SETTINGS,
  STATUS_ROLE_SHIPPING,
  STATUS_ROLE_TRANSPORTATION,
  STATUS_ROLE_WAREHOUSE,
  STATUS_ROLE_ZALO,
} from "constants/rolesTab";
// ----------------------------------------------------------------------

export function path(root: string, sublink: string, isRootSymbol?: "symbol") {
  return `${isRootSymbol ? "/" : ""}${root}/${sublink}`;
}

export const ROOT_PATH = "";
export const ROOT = "";

// ----------------------------------------------------------------------

export const PATH_AUTH = {
  root: path(ROOT_PATH, "/"),
  login: path(ROOT_PATH, "/login"),
};

// ----------------------------------------------------------------------

export const PATH_PAGE = {
  PHONE_LEAD: "phone-leads",
  TRANSPORTATION: "transportation-care",
  CDP: "cdp",
  PROMOTION: "promotions",
};

export type PhoneLeadTab =
  | "all"
  | "attributes"
  | "handling"
  | "order"
  | "no_order"
  | "new"
  | "report"
  | "user"
  | "waiting";

export type TRANSPORTATION_PATH_TYPE = "lateDelivery" | "wfd" | "returning" | "reportHandleStatus";

export type CDPTabsType = "users" | "ranks";

export enum PHONE_LEAD_PATH {
  STATUS = "status",
  REPORT_HANDLE_ITEM_BY_PRODUCT = "report-handle-item-by-product",
  REPORT_V1 = "v1",
  REPORT_V2 = "v2",
  ALL = "all",
  ATTRIBUTE = "attributes",
  SPAM = "spam",
  HANDLING = "handling",
  ORDER = "order",
  NEW = "new",
  NO_ORDER = "no-order",
  REPORT = "report",
  USER = "user",
  VOIP = "voip",
  VOIP_OUTBOUND = "outbound",
  VOIP_INBOUND = "inbound",
  VOIP_MISSED = "missed",
  WAITING = "waiting",
  BAD_DATA = "bad-data",
  REPORT_CRM = "report-crm",
  // spam menu item
  SPAM_CHECK = "spam-check",
  SPAM_IP = "ip",
  SPAM_PHONE = "phone",
  SPAM_KEYWORD = "keyword",
}

export enum ORDER_PATH {
  DETAIL = "detail",
  DRAFT = "draft",
  LIST = "list",
  COMPLETED = "completed",
  CANCEL = "cancel",
  ALL = "all",
  ITEM = "item",
  REPORT_DETAIL = "report-detail",
}

export enum ACCOUNTANT_PATH {
  REPORT = "report",
  REPORT_ORDER = "order",
  REPORT_ORDER_ITEM = "order-item",
  REPORT_KPI = "kpi",
  COLLATION = "collation",
  IMPORT_EXCEL_HISTORY = "import-excel",
  COLLATION_PAYMENT = "payment",
}

export const PATH_DASHBOARD: PathDashboardType = {
  [ROOT]: path(ROOT_PATH, ""),
  [ROLE_TAB.PROFILE]: path(ROOT_PATH, ROLE_TAB.PROFILE),
  [ROLE_TAB.DASHBOARD]: path(ROOT_PATH, ROLE_TAB.DASHBOARD),
  [ROLE_TAB.SALE_DASHBOARD]: path(ROOT_PATH, ROLE_TAB.SALE_DASHBOARD),
  [ROLE_TAB.MKT_DASHBOARD]: path(ROOT_PATH, ROLE_TAB.MKT_DASHBOARD),
  [ROLE_TAB.SALE_ONLINE_REPORT]: path(ROOT_PATH, ROLE_TAB.SALE_ONLINE_REPORT),
  [ROLE_TAB.ORDERS]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.ORDERS),
    [ORDER_PATH.LIST]: {
      [ROOT]: path(ROLE_TAB.ORDERS, ORDER_PATH.LIST),
      [ORDER_PATH.DRAFT]: path(`${ROLE_TAB.ORDERS}/${ORDER_PATH.LIST}`, ORDER_PATH.DRAFT),
      [ORDER_PATH.COMPLETED]: path(`${ROLE_TAB.ORDERS}/${ORDER_PATH.LIST}`, ORDER_PATH.COMPLETED),
      [ORDER_PATH.CANCEL]: path(`${ROLE_TAB.ORDERS}/${ORDER_PATH.LIST}`, ORDER_PATH.CANCEL),
      [ORDER_PATH.ALL]: path(`${ROLE_TAB.ORDERS}/${ORDER_PATH.LIST}`, ORDER_PATH.ALL),
    },
  },
  [ROLE_TAB.ACCOUNTANT]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.ACCOUNTANT),
    [ACCOUNTANT_PATH.REPORT]: {
      [ROOT]: path(ROLE_TAB.ACCOUNTANT, ACCOUNTANT_PATH.REPORT),
      [ACCOUNTANT_PATH.REPORT_ORDER]: path(
        `${ROLE_TAB.ACCOUNTANT}/${ACCOUNTANT_PATH.REPORT}`,
        ACCOUNTANT_PATH.REPORT_ORDER
      ),
      [ACCOUNTANT_PATH.REPORT_ORDER_ITEM]: path(
        `${ROLE_TAB.ACCOUNTANT}/${ACCOUNTANT_PATH.REPORT}`,
        ACCOUNTANT_PATH.REPORT_ORDER_ITEM
      ),
      [ACCOUNTANT_PATH.REPORT_KPI]: path(
        `${ROLE_TAB.ACCOUNTANT}/${ACCOUNTANT_PATH.REPORT}`,
        ACCOUNTANT_PATH.REPORT_KPI
      ),
    },
    [ACCOUNTANT_PATH.COLLATION]: {
      [ROOT]: path(ROLE_TAB.ACCOUNTANT, ACCOUNTANT_PATH.COLLATION),
      [ACCOUNTANT_PATH.IMPORT_EXCEL_HISTORY]: path(
        `${ROLE_TAB.ACCOUNTANT}/${ACCOUNTANT_PATH.COLLATION}`,
        ACCOUNTANT_PATH.IMPORT_EXCEL_HISTORY
      ),
      [ACCOUNTANT_PATH.COLLATION_PAYMENT]: path(
        `${ROLE_TAB.ACCOUNTANT}/${ACCOUNTANT_PATH.COLLATION}`,
        ACCOUNTANT_PATH.COLLATION_PAYMENT
      ),
    },
  },
  [ROLE_TAB.LEAD]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.LEAD),
    [PHONE_LEAD_PATH.VOIP]: {
      [ROOT]: path(ROLE_TAB.LEAD, PHONE_LEAD_PATH.VOIP),
      [PHONE_LEAD_PATH.ALL]: path(`${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.VOIP}`, PHONE_LEAD_PATH.ALL),
      [PHONE_LEAD_PATH.VOIP_INBOUND]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.VOIP}`,
        PHONE_LEAD_PATH.VOIP_INBOUND
      ),
      [PHONE_LEAD_PATH.VOIP_OUTBOUND]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.VOIP}`,
        PHONE_LEAD_PATH.VOIP_OUTBOUND
      ),
      [PHONE_LEAD_PATH.VOIP_MISSED]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.VOIP}`,
        PHONE_LEAD_PATH.VOIP_MISSED
      ),
    },
    [PHONE_LEAD_PATH.STATUS]: {
      [ROOT]: path(ROLE_TAB.LEAD, PHONE_LEAD_PATH.STATUS),
      [PHONE_LEAD_PATH.ALL]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.STATUS}`,
        PHONE_LEAD_PATH.ALL
      ),
      [PHONE_LEAD_PATH.ATTRIBUTE]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.STATUS}`,
        PHONE_LEAD_PATH.ATTRIBUTE
      ),
      [PHONE_LEAD_PATH.HANDLING]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.STATUS}`,
        PHONE_LEAD_PATH.HANDLING
      ),
      [PHONE_LEAD_PATH.ORDER]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.STATUS}`,
        PHONE_LEAD_PATH.ORDER
      ),
      [PHONE_LEAD_PATH.NEW]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.STATUS}`,
        PHONE_LEAD_PATH.NEW
      ),
      [PHONE_LEAD_PATH.NO_ORDER]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.STATUS}`,
        PHONE_LEAD_PATH.NO_ORDER
      ),
      [PHONE_LEAD_PATH.BAD_DATA]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.STATUS}`,
        PHONE_LEAD_PATH.BAD_DATA
      ),
      [PHONE_LEAD_PATH.SPAM]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.STATUS}`,
        PHONE_LEAD_PATH.SPAM
      ),
      [PHONE_LEAD_PATH.WAITING]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.STATUS}`,
        PHONE_LEAD_PATH.WAITING
      ),
    },
    [PHONE_LEAD_PATH.REPORT]: {
      [ROOT]: path(ROLE_TAB.LEAD, PHONE_LEAD_PATH.REPORT),
      [PHONE_LEAD_PATH.REPORT_V1]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.REPORT}`,
        PHONE_LEAD_PATH.REPORT_V1
      ),
      [PHONE_LEAD_PATH.REPORT_V2]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.REPORT}`,
        PHONE_LEAD_PATH.REPORT_V2
      ),
      [PHONE_LEAD_PATH.REPORT_HANDLE_ITEM_BY_PRODUCT]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.REPORT}`,
        PHONE_LEAD_PATH.REPORT_HANDLE_ITEM_BY_PRODUCT
      ),
      [PHONE_LEAD_PATH.REPORT_CRM]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.REPORT}`,
        PHONE_LEAD_PATH.REPORT_CRM
      ),
      [PHONE_LEAD_PATH.USER]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.REPORT}`,
        PHONE_LEAD_PATH.USER
      ),
      [PHONE_LEAD_PATH.VOIP]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.REPORT}`,
        PHONE_LEAD_PATH.VOIP
      ),
    },
    [PHONE_LEAD_PATH.SPAM_CHECK]: {
      [ROOT]: path(ROLE_TAB.LEAD, PHONE_LEAD_PATH.SPAM_CHECK),
      [PHONE_LEAD_PATH.SPAM_IP]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.SPAM_CHECK}`,
        PHONE_LEAD_PATH.SPAM_IP
      ),
      [PHONE_LEAD_PATH.SPAM_PHONE]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.SPAM_CHECK}`,
        PHONE_LEAD_PATH.SPAM_PHONE
      ),
      [PHONE_LEAD_PATH.SPAM_KEYWORD]: path(
        `${ROLE_TAB.LEAD}/${PHONE_LEAD_PATH.SPAM_CHECK}`,
        PHONE_LEAD_PATH.SPAM_KEYWORD
      ),
    },
  },
  [ROLE_TAB.TRANSPORTATION]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.TRANSPORTATION),
    [STATUS_ROLE_TRANSPORTATION.STATUS]: {
      [ROOT]: path(ROLE_TAB.TRANSPORTATION, STATUS_ROLE_TRANSPORTATION.STATUS),
      [STATUS_ROLE_TRANSPORTATION.NEW]: path(
        `${ROLE_TAB.TRANSPORTATION}/${STATUS_ROLE_TRANSPORTATION.STATUS}`,
        STATUS_ROLE_TRANSPORTATION.NEW
      ),
      [STATUS_ROLE_TRANSPORTATION.PENDING]: path(
        `${ROLE_TAB.TRANSPORTATION}/${STATUS_ROLE_TRANSPORTATION.STATUS}`,
        STATUS_ROLE_TRANSPORTATION.PENDING
      ),
      [STATUS_ROLE_TRANSPORTATION.PROCESSING]: path(
        `${ROLE_TAB.TRANSPORTATION}/${STATUS_ROLE_TRANSPORTATION.STATUS}`,
        STATUS_ROLE_TRANSPORTATION.PROCESSING
      ),
      [STATUS_ROLE_TRANSPORTATION.HANDLED]: path(
        `${ROLE_TAB.TRANSPORTATION}/${STATUS_ROLE_TRANSPORTATION.STATUS}`,
        STATUS_ROLE_TRANSPORTATION.HANDLED
      ),
      [STATUS_ROLE_TRANSPORTATION.COMPLETED]: path(
        `${ROLE_TAB.TRANSPORTATION}/${STATUS_ROLE_TRANSPORTATION.STATUS}`,
        STATUS_ROLE_TRANSPORTATION.COMPLETED
      ),
      [STATUS_ROLE_TRANSPORTATION.ALL]: path(
        `${ROLE_TAB.TRANSPORTATION}/${STATUS_ROLE_TRANSPORTATION.STATUS}`,
        STATUS_ROLE_TRANSPORTATION.ALL
      ),
    },

    [STATUS_ROLE_TRANSPORTATION.REPORT_ASSIGNED]: path(
      ROLE_TAB.TRANSPORTATION,
      STATUS_ROLE_TRANSPORTATION.REPORT_ASSIGNED
    ),
  },
  [ROLE_TAB.CDP]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.CDP),
    [STATUS_ROLE_CDP.USERS]: {
      [ROOT]: path(ROLE_TAB.CDP, STATUS_ROLE_CDP.USERS),
      [STATUS_ROLE_CDP.LIST]: path(
        `${ROLE_TAB.CDP}/${STATUS_ROLE_CDP.USERS}`,
        STATUS_ROLE_CDP.LIST
      ),
      [STATUS_ROLE_CDP.EXTERNAL_USERS]: path(
        `${ROLE_TAB.CDP}/${STATUS_ROLE_CDP.USERS}`,
        STATUS_ROLE_CDP.EXTERNAL_USERS
      ),
      [STATUS_ROLE_CDP.REPORTS]: path(
        `${ROLE_TAB.CDP}/${STATUS_ROLE_CDP.USERS}`,
        STATUS_ROLE_CDP.REPORTS
      ),
    },
    [STATUS_ROLE_CDP.DETAIL]: path(ROLE_TAB.CDP, STATUS_ROLE_CDP.DETAIL),
  },
  [ROLE_TAB.PROMOTION]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.PROMOTION),
    [PROMOTION_ROLES.ALL]: path(ROLE_TAB.PROMOTION, PROMOTION_ROLES.ALL),
    [PROMOTION_ROLES.ACTIVE]: path(ROLE_TAB.PROMOTION, PROMOTION_ROLES.ACTIVE),
    [PROMOTION_ROLES.INACTIVE]: path(ROLE_TAB.PROMOTION, PROMOTION_ROLES.INACTIVE),
    [PROMOTION_ROLES.DEACTIVED]: path(ROLE_TAB.PROMOTION, PROMOTION_ROLES.DEACTIVED),
  },
  [ROLE_TAB.SKYCOM_TABLE]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.SKYCOM_TABLE),
  },
  [ROLE_TAB.GOOGLE]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.GOOGLE),
    [STATUS_ROLE_GOOGLE.CUSTOMER_ACCOUNT]: path(
      ROLE_TAB.GOOGLE,
      STATUS_ROLE_GOOGLE.CUSTOMER_ACCOUNT
    ),
    [STATUS_ROLE_GOOGLE.CAMPAIGN_GOOGLE]: path(ROLE_TAB.GOOGLE, STATUS_ROLE_GOOGLE.CAMPAIGN_GOOGLE),
    [STATUS_ROLE_GOOGLE.ADGROUP_GOOGLE]: path(ROLE_TAB.GOOGLE, STATUS_ROLE_GOOGLE.ADGROUP_GOOGLE),
    [STATUS_ROLE_GOOGLE.AD_GOOGLE]: path(ROLE_TAB.GOOGLE, STATUS_ROLE_GOOGLE.AD_GOOGLE),
  },
  [ROLE_TAB.FACEBOOK]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.FACEBOOK),
    [STATUS_ROLE_FACEBOOK.AD_FACEBOOK]: path(ROLE_TAB.FACEBOOK, STATUS_ROLE_FACEBOOK.AD_FACEBOOK),
    [STATUS_ROLE_FACEBOOK.AD_FANPAGE]: path(ROLE_TAB.FACEBOOK, STATUS_ROLE_FACEBOOK.AD_FANPAGE),
    [STATUS_ROLE_FACEBOOK.REPORT_AD_FACEBOOK]: path(
      ROLE_TAB.FACEBOOK,
      STATUS_ROLE_FACEBOOK.REPORT_AD_FACEBOOK
    ),
    [STATUS_ROLE_FACEBOOK.REPORT_AD_FANPAGE]: path(
      ROLE_TAB.FACEBOOK,
      STATUS_ROLE_FACEBOOK.REPORT_AD_FANPAGE
    ),
  },
  [ROLE_TAB.CONTENT_ID]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.CONTENT_ID),
    [STATUS_ROLE_CONTENT_ID.TOTAL]: path(ROLE_TAB.CONTENT_ID, STATUS_ROLE_CONTENT_ID.TOTAL),
    [STATUS_ROLE_CONTENT_ID.ATTACH_PHONE]: path(
      ROLE_TAB.CONTENT_ID,
      STATUS_ROLE_CONTENT_ID.ATTACH_PHONE
    ),
    [STATUS_ROLE_CONTENT_ID.FACEBOOK]: path(ROLE_TAB.CONTENT_ID, STATUS_ROLE_CONTENT_ID.FACEBOOK),
    [STATUS_ROLE_CONTENT_ID.GOOGLE]: path(ROLE_TAB.CONTENT_ID, STATUS_ROLE_CONTENT_ID.GOOGLE),
    [STATUS_ROLE_CONTENT_ID.TIKTOK]: path(ROLE_TAB.CONTENT_ID, STATUS_ROLE_CONTENT_ID.TIKTOK),
    [STATUS_ROLE_CONTENT_ID.PHONE_LEAD]: path(
      ROLE_TAB.CONTENT_ID,
      STATUS_ROLE_CONTENT_ID.PHONE_LEAD
    ),
    [STATUS_ROLE_CONTENT_ID.ATTRIBUTES]: path(
      ROLE_TAB.CONTENT_ID,
      STATUS_ROLE_CONTENT_ID.ATTRIBUTES
    ),
    [STATUS_ROLE_CONTENT_ID.PIVOT]: path(ROLE_TAB.CONTENT_ID, STATUS_ROLE_CONTENT_ID.PIVOT),
  },
  [ROLE_TAB.CONTENT_DAILY]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.CONTENT_DAILY),
    [STATUS_ROLE_CONTENT_DAILY.OVERVIEW]: path(
      ROLE_TAB.CONTENT_DAILY,
      STATUS_ROLE_CONTENT_DAILY.OVERVIEW
    ),
    [STATUS_ROLE_CONTENT_DAILY.PIVOT]: path(
      ROLE_TAB.CONTENT_DAILY,
      STATUS_ROLE_CONTENT_DAILY.PIVOT
    ),
  },
  [ROLE_TAB.PRODUCT]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.PRODUCT),
    [STATUS_ROLE_PRODUCT.LIST_PRODUCT]: {
      [ROOT]: path(ROLE_TAB.PRODUCT, STATUS_ROLE_PRODUCT.LIST_PRODUCT),
      [STATUS_ROLE_LIST_PRODUCT.ALL]: path(
        `${ROLE_TAB.PRODUCT}/${STATUS_ROLE_PRODUCT.LIST_PRODUCT}`,
        STATUS_ROLE_LIST_PRODUCT.ALL
      ),
      [STATUS_ROLE_LIST_PRODUCT.SINGLE]: path(
        `${ROLE_TAB.PRODUCT}/${STATUS_ROLE_PRODUCT.LIST_PRODUCT}`,
        STATUS_ROLE_LIST_PRODUCT.SINGLE
      ),
      [STATUS_ROLE_LIST_PRODUCT.COMBO]: path(
        `${ROLE_TAB.PRODUCT}/${STATUS_ROLE_PRODUCT.LIST_PRODUCT}`,
        STATUS_ROLE_LIST_PRODUCT.COMBO
      ),
    },
    [STATUS_ROLE_PRODUCT.MAP_ECOMMERCE]: {
      [ROOT]: path(ROLE_TAB.PRODUCT, STATUS_ROLE_PRODUCT.MAP_ECOMMERCE),
      [STATUS_ROLE_ECOMMERCE.ALL]: path(
        `${ROLE_TAB.PRODUCT}/${STATUS_ROLE_PRODUCT.MAP_ECOMMERCE}`,
        STATUS_ROLE_ECOMMERCE.ALL
      ),
      [STATUS_ROLE_ECOMMERCE.LAZADA]: path(
        `${ROLE_TAB.PRODUCT}/${STATUS_ROLE_PRODUCT.MAP_ECOMMERCE}`,
        STATUS_ROLE_ECOMMERCE.LAZADA
      ),
      [STATUS_ROLE_ECOMMERCE.TIKTOK]: path(
        `${ROLE_TAB.PRODUCT}/${STATUS_ROLE_PRODUCT.MAP_ECOMMERCE}`,
        STATUS_ROLE_ECOMMERCE.TIKTOK
      ),
      [STATUS_ROLE_ECOMMERCE.SHOPEE]: path(
        `${ROLE_TAB.PRODUCT}/${STATUS_ROLE_PRODUCT.MAP_ECOMMERCE}`,
        STATUS_ROLE_ECOMMERCE.SHOPEE
      ),
    },
  },
  [ROLE_TAB.WAREHOUSE]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.WAREHOUSE),
    [STATUS_ROLE_WAREHOUSE.IMPORTS]: path(ROLE_TAB.WAREHOUSE, STATUS_ROLE_WAREHOUSE.IMPORTS),
    [STATUS_ROLE_WAREHOUSE.EXPORTS]: path(ROLE_TAB.WAREHOUSE, STATUS_ROLE_WAREHOUSE.EXPORTS),
    [STATUS_ROLE_WAREHOUSE.LIST_WAREHOUSE]: path(
      ROLE_TAB.WAREHOUSE,
      STATUS_ROLE_WAREHOUSE.LIST_WAREHOUSE
    ),
    [STATUS_ROLE_WAREHOUSE.TRANSFER]: path(ROLE_TAB.WAREHOUSE, STATUS_ROLE_WAREHOUSE.TRANSFER),
    [STATUS_ROLE_WAREHOUSE.STOCKTAKING]: path(
      ROLE_TAB.WAREHOUSE,
      STATUS_ROLE_WAREHOUSE.STOCKTAKING
    ),
    [STATUS_ROLE_WAREHOUSE.ATTRIBUTES]: path(ROLE_TAB.WAREHOUSE, STATUS_ROLE_WAREHOUSE.ATTRIBUTES),
    [STATUS_ROLE_WAREHOUSE.SCAN_EXPORT]: path(
      ROLE_TAB.WAREHOUSE,
      STATUS_ROLE_WAREHOUSE.SCAN_EXPORT
    ),
    [STATUS_ROLE_WAREHOUSE.REPORT_INVENTORY]: path(
      ROLE_TAB.WAREHOUSE,
      STATUS_ROLE_WAREHOUSE.REPORT_INVENTORY
    ),
    [STATUS_ROLE_WAREHOUSE.SCAN_LOGS]: path(ROLE_TAB.WAREHOUSE, STATUS_ROLE_WAREHOUSE.SCAN_LOGS),
    [STATUS_ROLE_WAREHOUSE.WAREHOUSE_LOGS]: path(
      ROLE_TAB.WAREHOUSE,
      STATUS_ROLE_WAREHOUSE.WAREHOUSE_LOGS
    ),
    [STATUS_ROLE_WAREHOUSE.REPORT_INVENTORY_ACTIVITIES]: path(
      ROLE_TAB.WAREHOUSE,
      STATUS_ROLE_WAREHOUSE.REPORT_INVENTORY_ACTIVITIES
    ),
  },
  [ROLE_TAB.CSKH]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.CSKH),
    [STATUS_ROLE_AIRTABLE.ALL]: path(ROLE_TAB.CSKH, STATUS_ROLE_AIRTABLE.ALL),
    [STATUS_ROLE_AIRTABLE.NEW]: path(ROLE_TAB.CSKH, STATUS_ROLE_AIRTABLE.NEW),
    [STATUS_ROLE_AIRTABLE.HANDLING]: path(ROLE_TAB.CSKH, STATUS_ROLE_AIRTABLE.HANDLING),
    [STATUS_ROLE_AIRTABLE.COMPLETED]: path(ROLE_TAB.CSKH, STATUS_ROLE_AIRTABLE.COMPLETED),
  },
  [ROLE_TAB.SHIPPING]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.SHIPPING),
    [STATUS_ROLE_SHIPPING.ALL]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.ALL),
    [STATUS_ROLE_SHIPPING.PICKING]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.PICKING),
    [STATUS_ROLE_SHIPPING.DELIVERING]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.DELIVERING),
    [STATUS_ROLE_SHIPPING.RETURNING]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.RETURNING),
    [STATUS_ROLE_SHIPPING.RETURNED]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.RETURNED),
    [STATUS_ROLE_SHIPPING.SUCCESS]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.SUCCESS),
    [STATUS_ROLE_SHIPPING.LOST]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.LOST),
    [STATUS_ROLE_SHIPPING.CANCELLED]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.CANCELLED),
    [STATUS_ROLE_SHIPPING.WAIT_DELIVERY]: path(
      ROLE_TAB.SHIPPING,
      STATUS_ROLE_SHIPPING.WAIT_DELIVERY
    ),
    [STATUS_ROLE_SHIPPING.ATTRIBUTES]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.ATTRIBUTES),
    [STATUS_ROLE_SHIPPING.COMPLETED]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.COMPLETED),
    [STATUS_ROLE_SHIPPING.REPORT]: path(ROLE_TAB.SHIPPING, STATUS_ROLE_SHIPPING.REPORT),
  },
  [ROLE_TAB.REPORT_REVENUE]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.REPORT_REVENUE),
    [STATUS_ROLE_REPORT_REVENUE.BY_DATE]: path(
      ROLE_TAB.REPORT_REVENUE,
      STATUS_ROLE_REPORT_REVENUE.BY_DATE
    ),
    [STATUS_ROLE_REPORT_REVENUE.BY_CHANNEL]: path(
      ROLE_TAB.REPORT_REVENUE,
      STATUS_ROLE_REPORT_REVENUE.BY_CHANNEL
    ),
    [STATUS_ROLE_REPORT_REVENUE.BY_PRODUCT]: path(
      ROLE_TAB.REPORT_REVENUE,
      STATUS_ROLE_REPORT_REVENUE.BY_PRODUCT
    ),
    [STATUS_ROLE_REPORT_REVENUE.BY_PROVINCE]: path(
      ROLE_TAB.REPORT_REVENUE,
      STATUS_ROLE_REPORT_REVENUE.BY_PROVINCE
    ),
    [STATUS_ROLE_REPORT_REVENUE.BY_CREATED_BY]: path(
      ROLE_TAB.REPORT_REVENUE,
      STATUS_ROLE_REPORT_REVENUE.BY_CREATED_BY
    ),
  },
  [ROLE_TAB.SETTINGS]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.SETTINGS),
    [STATUS_ROLE_SETTINGS.SKYLINK_ACCOUNT]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.SKYLINK_ACCOUNT
    ),
    [STATUS_ROLE_SETTINGS.FACEBOOK_ACCOUNT]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.FACEBOOK_ACCOUNT
    ),
    [STATUS_ROLE_SETTINGS.AD_FACEBOOK_ACCOUNT]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.AD_FACEBOOK_ACCOUNT
    ),
    [STATUS_ROLE_SETTINGS.FANPAGE_ACCOUNT]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.FANPAGE_ACCOUNT
    ),
    [STATUS_ROLE_SETTINGS.GOOGLE_ACCOUNT_BM]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.GOOGLE_ACCOUNT_BM
    ),
    [STATUS_ROLE_SETTINGS.CUSTOMER_ACCOUNT]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.CUSTOMER_ACCOUNT
    ),
    [STATUS_ROLE_SETTINGS.TIKTOK_ACCOUNT]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.TIKTOK_ACCOUNT
    ),
    [STATUS_ROLE_SETTINGS.TIKTOK_ADS_ACCOUNT]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.TIKTOK_ADS_ACCOUNT
    ),
    [STATUS_ROLE_SETTINGS.TIKTOK_BM_ACCOUNT]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.TIKTOK_BM_ACCOUNT
    ),
    [STATUS_ROLE_SETTINGS.LAZADA_ACCOUNT]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.LAZADA_ACCOUNT
    ),
    [STATUS_ROLE_SETTINGS.TIKI_ACCOUNT]: path(ROLE_TAB.SETTINGS, STATUS_ROLE_SETTINGS.TIKI_ACCOUNT),
    [STATUS_ROLE_SETTINGS.SHOPEE_ACCOUNT]: path(
      ROLE_TAB.SETTINGS,
      STATUS_ROLE_SETTINGS.SHOPEE_ACCOUNT
    ),
    [STATUS_ROLE_SETTINGS.ZALO_ACCOUNT]: path(ROLE_TAB.SETTINGS, STATUS_ROLE_SETTINGS.ZALO_ACCOUNT),
    [STATUS_ROLE_SETTINGS.CDP_CARD]: path(ROLE_TAB.SETTINGS, STATUS_ROLE_SETTINGS.CDP_CARD),
    [STATUS_ROLE_SETTINGS.ROLE]: path(ROLE_TAB.SETTINGS, STATUS_ROLE_SETTINGS.ROLE),
  },
  [ROLE_TAB.ATTRIBUTE]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.ATTRIBUTE),
    [STATUS_ROLE_ATTRIBUTE.SETTING]: path(ROLE_TAB.ATTRIBUTE, STATUS_ROLE_ATTRIBUTE.SETTING),
    [STATUS_ROLE_ATTRIBUTE.LEADS]: path(ROLE_TAB.ATTRIBUTE, STATUS_ROLE_ATTRIBUTE.LEADS),
    [STATUS_ROLE_ATTRIBUTE.TRANSPORTATION]: path(
      ROLE_TAB.ATTRIBUTE,
      STATUS_ROLE_ATTRIBUTE.TRANSPORTATION
    ),
    [STATUS_ROLE_ATTRIBUTE.CDP]: path(ROLE_TAB.ATTRIBUTE, STATUS_ROLE_ATTRIBUTE.CDP),
    [STATUS_ROLE_ATTRIBUTE.ORDER]: path(ROLE_TAB.ATTRIBUTE, STATUS_ROLE_ATTRIBUTE.ORDER),
    [STATUS_ROLE_ATTRIBUTE.SHIPPING]: path(ROLE_TAB.ATTRIBUTE, STATUS_ROLE_ATTRIBUTE.SHIPPING),
    [STATUS_ROLE_ATTRIBUTE.PRODUCT]: path(ROLE_TAB.ATTRIBUTE, STATUS_ROLE_ATTRIBUTE.PRODUCT),
    [STATUS_ROLE_ATTRIBUTE.WAREHOUSE]: path(ROLE_TAB.ATTRIBUTE, STATUS_ROLE_ATTRIBUTE.WAREHOUSE),
    [STATUS_ROLE_ATTRIBUTE.AIRTABLE]: path(ROLE_TAB.ATTRIBUTE, STATUS_ROLE_ATTRIBUTE.AIRTABLE),
    [STATUS_ROLE_ATTRIBUTE.MANAGE_FILE]: path(
      ROLE_TAB.ATTRIBUTE,
      STATUS_ROLE_ATTRIBUTE.MANAGE_FILE
    ),
    [STATUS_ROLE_ATTRIBUTE.DATA_FLOW]: path(ROLE_TAB.ATTRIBUTE, STATUS_ROLE_ATTRIBUTE.DATA_FLOW),
  },
  [ROLE_TAB.MANAGE_FILE]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.MANAGE_FILE),
    [STATUS_ROLE_MANAGE_FILE.MANAGE]: path(ROLE_TAB.MANAGE_FILE, STATUS_ROLE_MANAGE_FILE.MANAGE),
    [STATUS_ROLE_MANAGE_FILE.GROUP]: path(ROLE_TAB.MANAGE_FILE, STATUS_ROLE_MANAGE_FILE.GROUP),
  },
  [ROLE_TAB.ZALO]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.ZALO),
    [STATUS_ROLE_ZALO.FOLLOWER_ACCOUNT]: path(ROLE_TAB.ZALO, STATUS_ROLE_ZALO.FOLLOWER_ACCOUNT),
    [STATUS_ROLE_ZALO.NOTIFICATION]: path(ROLE_TAB.ZALO, STATUS_ROLE_ZALO.NOTIFICATION),
    [STATUS_ROLE_ZALO.DASHBOARD]: path(ROLE_TAB.ZALO, STATUS_ROLE_ZALO.DASHBOARD),
  },
  [ROLE_TAB.SUPPORT]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.SUPPORT),
  },
  [ROLE_TAB.DATA_FLOW]: {
    [ROOT]: path(ROOT_PATH, ROLE_TAB.DATA_FLOW),
    [STATUS_ROLE_DATA_FLOW.LIST]: path(ROLE_TAB.DATA_FLOW, STATUS_ROLE_DATA_FLOW.LIST),
    [STATUS_ROLE_DATA_FLOW.HANDLE]: path(ROLE_TAB.DATA_FLOW, STATUS_ROLE_DATA_FLOW.HANDLE),
    [STATUS_ROLE_DATA_FLOW.ACCOUNT]: path(ROLE_TAB.DATA_FLOW, STATUS_ROLE_DATA_FLOW.ACCOUNT),
  },
};
