import {
  PROMOTION_ROLES,
  ROLE_TAB,
  STATUS_ROLE_AIRTABLE,
  STATUS_ROLE_ATTRIBUTE,
  STATUS_ROLE_CDP,
  STATUS_ROLE_CONTENT_DAILY,
  STATUS_ROLE_CONTENT_ID,
  STATUS_ROLE_DASHBOARD,
  STATUS_ROLE_DATA_FLOW,
  STATUS_ROLE_ECOMMERCE,
  STATUS_ROLE_FACEBOOK,
  STATUS_ROLE_GOOGLE,
  STATUS_ROLE_LIST_PRODUCT,
  STATUS_ROLE_MANAGE_FILE,
  STATUS_ROLE_PRODUCT,
  STATUS_ROLE_ACCOUNTANT,
  STATUS_ROLE_REPORT_REVENUE,
  STATUS_ROLE_SETTINGS,
  STATUS_ROLE_SHIPPING,
  STATUS_ROLE_TRANSPORTATION,
  STATUS_ROLE_WAREHOUSE,
  STATUS_ROLE_ZALO,
} from "constants/rolesTab";
import { ACCOUNTANT_PATH, ORDER_PATH, PHONE_LEAD_PATH, ROOT } from "routes/paths";

export interface PathDashboardType {
  [ROOT]: string;
  [ROLE_TAB.PROFILE]: string;
  [STATUS_ROLE_DASHBOARD.DASHBOARD]: string;
  [STATUS_ROLE_DASHBOARD.SALE_DASHBOARD]: string;
  [STATUS_ROLE_DASHBOARD.MKT_DASHBOARD]: string;
  [STATUS_ROLE_DASHBOARD.SALE_ONLINE_REPORT]: string;
  [ROLE_TAB.ORDERS]: {
    [ROOT]: string;
    [ORDER_PATH.LIST]: {
      [ROOT]: string;
      [ORDER_PATH.DRAFT]: string;
      [ORDER_PATH.COMPLETED]: string;
      [ORDER_PATH.CANCEL]: string;
      [ORDER_PATH.ALL]: string;
    };
  };
  [ROLE_TAB.GOOGLE]: {
    [ROOT]: string;
    [STATUS_ROLE_GOOGLE.CUSTOMER_ACCOUNT]: string;
    [STATUS_ROLE_GOOGLE.CAMPAIGN_GOOGLE]: string;
    [STATUS_ROLE_GOOGLE.ADGROUP_GOOGLE]: string;
    [STATUS_ROLE_GOOGLE.AD_GOOGLE]: string;
  };
  [ROLE_TAB.FACEBOOK]: {
    [ROOT]: string;
    [STATUS_ROLE_FACEBOOK.AD_FACEBOOK]: string;
    [STATUS_ROLE_FACEBOOK.AD_FANPAGE]: string;
    [STATUS_ROLE_FACEBOOK.REPORT_AD_FACEBOOK]: string;
    [STATUS_ROLE_FACEBOOK.REPORT_AD_FANPAGE]: string;
  };
  [ROLE_TAB.CONTENT_ID]: {
    [ROOT]: string;
    [STATUS_ROLE_CONTENT_ID.TOTAL]: string;
    [STATUS_ROLE_CONTENT_ID.ATTACH_PHONE]: string;
    [STATUS_ROLE_CONTENT_ID.FACEBOOK]: string;
    [STATUS_ROLE_CONTENT_ID.GOOGLE]: string;
    [STATUS_ROLE_CONTENT_ID.TIKTOK]: string;
    [STATUS_ROLE_CONTENT_ID.PHONE_LEAD]: string;
    [STATUS_ROLE_CONTENT_ID.ATTRIBUTES]: string;
    [STATUS_ROLE_CONTENT_ID.ATTRIBUTES]: string;
    [STATUS_ROLE_CONTENT_ID.PIVOT]: string;
  };
  [ROLE_TAB.CONTENT_DAILY]: {
    [ROOT]: string;
    [STATUS_ROLE_CONTENT_DAILY.OVERVIEW]: string;
    [STATUS_ROLE_CONTENT_DAILY.PIVOT]: string;
  };
  [ROLE_TAB.PRODUCT]: {
    [ROOT]: string;
    [STATUS_ROLE_PRODUCT.LIST_PRODUCT]: {
      [ROOT]: string;
      [STATUS_ROLE_LIST_PRODUCT.ALL]: string;
      [STATUS_ROLE_LIST_PRODUCT.SINGLE]: string;
      [STATUS_ROLE_LIST_PRODUCT.COMBO]: string;
    };
    [STATUS_ROLE_PRODUCT.MAP_ECOMMERCE]: {
      [ROOT]: string;
      [STATUS_ROLE_ECOMMERCE.ALL]: string;
      [STATUS_ROLE_ECOMMERCE.LAZADA]: string;
      [STATUS_ROLE_ECOMMERCE.TIKTOK]: string;
      [STATUS_ROLE_ECOMMERCE.SHOPEE]: string;
    };
  };
  [ROLE_TAB.WAREHOUSE]: {
    [ROOT]: string;
    [STATUS_ROLE_WAREHOUSE.IMPORTS]: string;
    [STATUS_ROLE_WAREHOUSE.EXPORTS]: string;
    [STATUS_ROLE_WAREHOUSE.LIST_WAREHOUSE]: string;
    [STATUS_ROLE_WAREHOUSE.TRANSFER]: string;
    [STATUS_ROLE_WAREHOUSE.STOCKTAKING]: string;
    [STATUS_ROLE_WAREHOUSE.ATTRIBUTES]: string;
    [STATUS_ROLE_WAREHOUSE.SCAN_EXPORT]: string;
    [STATUS_ROLE_WAREHOUSE.REPORT_INVENTORY]: string;
    [STATUS_ROLE_WAREHOUSE.SCAN_LOGS]: string;
    [STATUS_ROLE_WAREHOUSE.WAREHOUSE_LOGS]: string;
    [STATUS_ROLE_WAREHOUSE.REPORT_INVENTORY_ACTIVITIES]: string;
  };
  [ROLE_TAB.CSKH]: {
    [ROOT]: string;
    [STATUS_ROLE_AIRTABLE.ALL]: string;
    [STATUS_ROLE_AIRTABLE.NEW]: string;
    [STATUS_ROLE_AIRTABLE.HANDLING]: string;
    [STATUS_ROLE_AIRTABLE.COMPLETED]: string;
  };
  [ROLE_TAB.SHIPPING]: {
    [ROOT]: string;
    [STATUS_ROLE_SHIPPING.ALL]: string;
    [STATUS_ROLE_SHIPPING.PICKING]: string;
    [STATUS_ROLE_SHIPPING.DELIVERING]: string;
    [STATUS_ROLE_SHIPPING.RETURNING]: string;
    [STATUS_ROLE_SHIPPING.RETURNED]: string;
    [STATUS_ROLE_SHIPPING.SUCCESS]: string;
    [STATUS_ROLE_SHIPPING.LOST]: string;
    [STATUS_ROLE_SHIPPING.CANCELLED]: string;
    [STATUS_ROLE_SHIPPING.WAIT_DELIVERY]: string;
    [STATUS_ROLE_SHIPPING.ATTRIBUTES]: string;
    [STATUS_ROLE_SHIPPING.COMPLETED]: string;
    [STATUS_ROLE_SHIPPING.REPORT]: string;
  };
  [ROLE_TAB.REPORT_REVENUE]: {
    [ROOT]: string;
    [STATUS_ROLE_REPORT_REVENUE.BY_DATE]: string;
    [STATUS_ROLE_REPORT_REVENUE.BY_CHANNEL]: string;
    [STATUS_ROLE_REPORT_REVENUE.BY_PRODUCT]: string;
    [STATUS_ROLE_REPORT_REVENUE.BY_PROVINCE]: string;
    [STATUS_ROLE_REPORT_REVENUE.BY_CREATED_BY]: string;
  };
  [ROLE_TAB.ACCOUNTANT]: {
    [ROOT]: string;
    [ACCOUNTANT_PATH.REPORT]: {
      [ROOT]: string;
      [ACCOUNTANT_PATH.REPORT_ORDER]: string;
      [ACCOUNTANT_PATH.REPORT_ORDER_ITEM]: string;
      [ACCOUNTANT_PATH.REPORT_KPI]: string;
    };
    [ACCOUNTANT_PATH.COLLATION]: {
      [ROOT]: string;
      [ACCOUNTANT_PATH.IMPORT_EXCEL_HISTORY]: string;
      [ACCOUNTANT_PATH.COLLATION_PAYMENT]: string;
    };
  };
  [ROLE_TAB.SETTINGS]: {
    [ROOT]: string;
    [STATUS_ROLE_SETTINGS.SKYLINK_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.FACEBOOK_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.AD_FACEBOOK_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.FANPAGE_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.GOOGLE_ACCOUNT_BM]: string;
    [STATUS_ROLE_SETTINGS.CUSTOMER_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.TIKTOK_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.TIKTOK_ADS_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.TIKTOK_BM_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.LAZADA_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.TIKI_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.SHOPEE_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.ZALO_ACCOUNT]: string;
    [STATUS_ROLE_SETTINGS.CDP_CARD]: string;
    [STATUS_ROLE_SETTINGS.ROLE]: string;
  };
  [ROLE_TAB.ATTRIBUTE]: {
    [ROOT]: string;
    [STATUS_ROLE_ATTRIBUTE.SETTING]: string;
    [STATUS_ROLE_ATTRIBUTE.LEADS]: string;
    [STATUS_ROLE_ATTRIBUTE.TRANSPORTATION]: string;
    [STATUS_ROLE_ATTRIBUTE.CDP]: string;
    [STATUS_ROLE_ATTRIBUTE.ORDER]: string;
    [STATUS_ROLE_ATTRIBUTE.SHIPPING]: string;
    [STATUS_ROLE_ATTRIBUTE.PRODUCT]: string;
    [STATUS_ROLE_ATTRIBUTE.WAREHOUSE]: string;
    [STATUS_ROLE_ATTRIBUTE.AIRTABLE]: string;
    [STATUS_ROLE_ATTRIBUTE.MANAGE_FILE]: string;
    [STATUS_ROLE_ATTRIBUTE.DATA_FLOW]: string;
  };
  [ROLE_TAB.MANAGE_FILE]: {
    [ROOT]: string;
    [STATUS_ROLE_MANAGE_FILE.MANAGE]: string;
    [STATUS_ROLE_MANAGE_FILE.GROUP]: string;
  };
  [ROLE_TAB.ZALO]: {
    [ROOT]: string;
    [STATUS_ROLE_ZALO.FOLLOWER_ACCOUNT]: string;
    [STATUS_ROLE_ZALO.NOTIFICATION]: string;
    [STATUS_ROLE_ZALO.DASHBOARD]: string;
  };
  [ROLE_TAB.TRANSPORTATION]: {
    [ROOT]: string;
    [STATUS_ROLE_TRANSPORTATION.STATUS]: {
      [ROOT]: string;
      [STATUS_ROLE_TRANSPORTATION.NEW]: string;
      [STATUS_ROLE_TRANSPORTATION.PENDING]: string;
      [STATUS_ROLE_TRANSPORTATION.PROCESSING]: string;
      [STATUS_ROLE_TRANSPORTATION.HANDLED]: string;
      [STATUS_ROLE_TRANSPORTATION.COMPLETED]: string;
      [STATUS_ROLE_TRANSPORTATION.ALL]: string;
    };
    [STATUS_ROLE_TRANSPORTATION.REPORT_ASSIGNED]: string;
  };
  [ROLE_TAB.CDP]: {
    [ROOT]: string;
    [STATUS_ROLE_CDP.USERS]: {
      [ROOT]: string;
      [STATUS_ROLE_CDP.LIST]: string;
      [STATUS_ROLE_CDP.REPORTS]: string;
      [STATUS_ROLE_CDP.EXTERNAL_USERS]: string;
    };
    [STATUS_ROLE_CDP.DETAIL]: string;
  };
  [ROLE_TAB.PROMOTION]: {
    [ROOT]: string;
    [PROMOTION_ROLES.ALL]: string;
    [PROMOTION_ROLES.ACTIVE]: string;
    [PROMOTION_ROLES.INACTIVE]: string;
    [PROMOTION_ROLES.DEACTIVED]: string;
  };
  [ROLE_TAB.LEAD]: {
    [ROOT]: string;
    [PHONE_LEAD_PATH.STATUS]: {
      [ROOT]: string;
      [PHONE_LEAD_PATH.ALL]: string;
      [PHONE_LEAD_PATH.ATTRIBUTE]: string;
      [PHONE_LEAD_PATH.HANDLING]: string;
      [PHONE_LEAD_PATH.ORDER]: string;
      [PHONE_LEAD_PATH.NEW]: string;
      [PHONE_LEAD_PATH.NO_ORDER]: string;
      [PHONE_LEAD_PATH.BAD_DATA]: string;
      [PHONE_LEAD_PATH.SPAM]: string;
      [PHONE_LEAD_PATH.WAITING]: string;
    };
    [PHONE_LEAD_PATH.VOIP]: {
      [ROOT]: string;
      [PHONE_LEAD_PATH.ALL]: string;
      [PHONE_LEAD_PATH.VOIP_INBOUND]: string;
      [PHONE_LEAD_PATH.VOIP_OUTBOUND]: string;
      [PHONE_LEAD_PATH.VOIP_MISSED]: string;
    };
    [PHONE_LEAD_PATH.REPORT]: {
      [ROOT]: string;
      [PHONE_LEAD_PATH.REPORT_V1]: string;
      [PHONE_LEAD_PATH.REPORT_V2]: string;
      [PHONE_LEAD_PATH.REPORT_HANDLE_ITEM_BY_PRODUCT]: string;
      [PHONE_LEAD_PATH.REPORT_CRM]: string;
      [PHONE_LEAD_PATH.USER]: string;
      [PHONE_LEAD_PATH.VOIP]: string;
    };
    [PHONE_LEAD_PATH.SPAM_CHECK]: {
      [ROOT]: string;
      [PHONE_LEAD_PATH.SPAM_IP]: string;
      [PHONE_LEAD_PATH.SPAM_PHONE]: string;
      [PHONE_LEAD_PATH.SPAM_KEYWORD]: string;
    };
  };
  [ROLE_TAB.DATA_FLOW]: {
    [ROOT]: string;
    [STATUS_ROLE_DATA_FLOW.LIST]: string;
    [STATUS_ROLE_DATA_FLOW.HANDLE]: string;
    [STATUS_ROLE_DATA_FLOW.ACCOUNT]: string;
  };
  [ROLE_TAB.SUPPORT]: {
    [ROOT]: string;
  };
  [ROLE_TAB.SKYCOM_TABLE]: {
    [ROOT]: string;
  };
}
