import { USER_ROLES } from "constants/userRoles";
import {
  ROLE_OPTION,
  ROLE_TAB,
  STATUS_ROLE_CDP,
  STATUS_ROLE_DASHBOARD,
  STATUS_ROLE_FACEBOOK,
  STATUS_ROLE_GOOGLE,
  STATUS_ROLE_LEAD,
  STATUS_ROLE_SETTINGS,
  STATUS_ROLE_ORDERS,
  PROMOTION_ROLES,
  ROLE_TYPE,
  GENERAL_ROLES,
} from "./rolesTab";

const ROLE_OPTIONS: {
  [key in ROLE_TAB]: {
    [key: string]: ROLE_TYPE;
  };
} = {
  [ROLE_TAB.LEAD]: {
    [STATUS_ROLE_LEAD.REPORT]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_LEAD.ADD_LEAD]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_LEAD.STATUS]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_LEAD.HANDLE_BY]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_LEAD.VOIP]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_LEAD.REPORT_DAILY_HANDLE_BY]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_LEAD.IMPORT_LEAD_EXCEL]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_LEAD.DATA_STATUS]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_LEAD.ACCOUNTS]: ROLE_OPTION.NO_PERMISSION,
  },
  [ROLE_TAB.CDP]: {
    [STATUS_ROLE_CDP.HANDLE]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_CDP.USERS]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_CDP.ADD]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_CDP.CUSTOMER_CARE_STAFF]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_CDP.PHONE]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_CDP.REPORTS]: ROLE_OPTION.NO_PERMISSION,
  },
  [ROLE_TAB.ORDERS]: {
    [STATUS_ROLE_ORDERS.HANDLE]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_ORDERS.SHIPPING]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_ORDERS.CANCEL]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_ORDERS.CONFIRM]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_ORDERS.PAYMENT]: ROLE_OPTION.NO_PERMISSION,
  },
  [ROLE_TAB.DASHBOARD]: {
    [STATUS_ROLE_DASHBOARD.DASHBOARD]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_DASHBOARD.SALE_DASHBOARD]: ROLE_OPTION.NO_PERMISSION,
  },
  [ROLE_TAB.FACEBOOK]: {
    [STATUS_ROLE_FACEBOOK.AD_FACEBOOK]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_FACEBOOK.AD_FANPAGE]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_FACEBOOK.REPORT_AD_FACEBOOK]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_FACEBOOK.REPORT_AD_FANPAGE]: ROLE_OPTION.NO_PERMISSION,
  },
  [ROLE_TAB.GOOGLE]: {
    [STATUS_ROLE_GOOGLE.CUSTOMER_ACCOUNT]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_GOOGLE.CAMPAIGN_GOOGLE]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_GOOGLE.ADGROUP_GOOGLE]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_GOOGLE.AD_GOOGLE]: ROLE_OPTION.NO_PERMISSION,
  },
  [ROLE_TAB.SETTINGS]: {
    [STATUS_ROLE_SETTINGS.SKYLINK_ACCOUNT]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_SETTINGS.FACEBOOK_ACCOUNT]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_SETTINGS.AD_FACEBOOK_ACCOUNT]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_SETTINGS.FANPAGE_ACCOUNT]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_SETTINGS.GOOGLE_ACCOUNT_BM]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_SETTINGS.CUSTOMER_ACCOUNT]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_SETTINGS.CDP_CARD]: ROLE_OPTION.NO_PERMISSION,
    [STATUS_ROLE_SETTINGS.ROLE]: ROLE_OPTION.READ_AND_WRITE,
    [STATUS_ROLE_SETTINGS.ATTRIBUTE]: ROLE_OPTION.READ_AND_WRITE,
  },
  [ROLE_TAB.PROMOTION]: {
    [PROMOTION_ROLES.STATUS]: ROLE_OPTION.NO_PERMISSION,
    [PROMOTION_ROLES.HANDLE]: ROLE_OPTION.NO_PERMISSION,
  },
  [ROLE_TAB.SALE_ONLINE_REPORT]: {
    [STATUS_ROLE_DASHBOARD.SALE_ONLINE_REPORT]: ROLE_OPTION.NO_PERMISSION,
  },
  root: {},
  zalo: {},
  product: {},
  [ROLE_TAB.CSKH]: {},
  transportation: {},
  warehouse: {},
  shipping: {},
  attribute: {},
  profile: {},
  [ROLE_TAB.CONTENT_ID]: {},
  [ROLE_TAB.MANAGE_FILE]: {},
  [ROLE_TAB.REPORT_REVENUE]: {},
  [ROLE_TAB.MKT_DASHBOARD]: {},
  [ROLE_TAB.SALE_DASHBOARD]: {},
  [ROLE_TAB.ACCOUNTANT]: {},
  [ROLE_TAB.GENERAL]: {
    [GENERAL_ROLES.EXPORT_EXCEL]: ROLE_OPTION.NO_PERMISSION,
  },
  [ROLE_TAB.SUPPORT]: {},
  [ROLE_TAB.DATA_FLOW]: {},
  [ROLE_TAB.SKYCOM_TABLE]: {},
  [ROLE_TAB.CONTENT_DAILY]: {},
};

export const ROLE_DEFAULT = {
  [USER_ROLES.ROLE_ADMIN]: ROLE_OPTIONS,
  [USER_ROLES.ROLE_SALES]: ROLE_OPTIONS,
  [USER_ROLES.ROLE_LEADER_SALES]: ROLE_OPTIONS,
  [USER_ROLES.ROLE_MARKETING]: ROLE_OPTIONS,
  [USER_ROLES.ROLE_CONTENT]: ROLE_OPTIONS,
  [USER_ROLES.ROLE_MARKETING_CLBT]: ROLE_OPTIONS,
  [USER_ROLES.ROLE_QA]: ROLE_OPTIONS,
};
