export const translate = {
  overview: "Tổng quan",
  title: "Vietnames",
  introduction: "",
  fanpage: "Fanpage",
  data_status: "Trạng thái dữ liệu",
  handle_by: "Chia số",
  created_by: "Người tạo",
  campaign_objective: "Theo campaign",
  channel: "Kênh bán hàng",
  lead_status: "Trạng thái đơn",
  creator: "Người tạo",
  handler: "Người xử lý",
  landing_page_domain: "URL sản phẩm trên ladipage",
  selection: "--Chọn--",
  fail_reason: "Lý do không mua",
  handle_status: "Số lần gọi",
  attribute: "Thuộc tính",
  handle_reason: "Lý do đang xử lý",
  bad_data_reason: "Lý do dữ liệu KCL",
  by_date: "Theo ngày",
  by_phone: "Theo SĐT",
  targeting: "Mục tiêu",
  comment: "Bình luận",
  activities: "Hoạt động",
  campaign: "Chiến dịch",
  inventory: "Hàng tồn kho",
  post: "Bài viết",
  by_team: "Theo team",
  by_objective: "Theo mục tiêu",
  button: {
    add: "Thêm",
    handle: "Xử lý",
    edit: "Chỉnh sửa",
    cancel: "Hủy",
    delete: "Xóa",
    update: "Cập nhật",
    create: "Tạo",
  },
  update: "Cập nhật",
  add_15_minutes: "Thêm 15 phút",
  are_you_sure_delete: "Bạn chắc chắn muốn xóa?",
  phone_lead: {
    new: "Mới",
    waiting: "Chờ xử lý",
    handling: "Đang xử lý",
    no_order: "Không mua",
    order: "Có mua",
    all: "Tất cả",
    report: "Báo cáo",
    attributes: "Thuộc tính",
    user: "Tài khoản",
    history: "Lịch sử",
    is_exist: "SĐT trùng",
    ad_channel: "Kênh quảng cáo",
    ad_id_content: "ID content",
    is_new_customer: "Khách hàng mới",
    additional_data: "Dữ liệu liên quan",
    bad_data_reason: "Lý do dữ liệu KCL",
    call_later_at: "Ngày gọi lại",
    channel: "Kênh bán hàng",
    created_by: "Người tạo",
    data_status: "Trạng thái dữ liệu",
    fail_reason: "Lý do không mua",
    fanpage: "Fanpage",
    handle_by: "Người xử lý",
    handle_reason: "Lý do xử lý",
    handle_status: "Trạng thái xử lý",
    handler_assigned_at: "Ngày gán người xử lý",
    id: "ID",
    ip_address: "Địa chỉ IP",
    is_duplicated_ip: "Trùng IP",
    is_existed: "Trùng SĐT",
    is_valid: "SĐT sai",
    landing_page_url: "Đường dẫn sản phẩm",
    lead_status: "Trạng thái đơn",
    modified: "Ngày xử lý",
    modified_by: "Người xử lý",
    name: "Tên",
    note: "Ghi chú",
    order_information: "Thông tin đơn hàng",
    os: "Hệ điều hành",
    phone: "SĐT",
    product: "Sản phẩm",
    recent_handling: "Thời gian xử lý(Phút)",
  },
  handle_status_field: {
    call: "Gọi lần ",
    not: "Chưa có",
  },
  product: {
    warehouse: "Kho xưởng",
    supplier: "Nhà phân phối",
  },
  phone_lead_report: {
    total: "Tổng",
    buy_rate: "Tỷ lệ chốt",
    pre_qualified: "SĐT CL trước xử lý",
    post_qualified: "SĐT CL sau xử lý",
    pre_not_qualified: "SĐT KCL trước xử lý",
    post_not_qualified: "SĐT KCL sau xử lý",
    processing: "Đang xử lý",
    processed: "Đã xử lý",
    buy: "Có mua",
    not_buy: "Không mua",
    consider: "Đang tham khảo",
    data_status: "Trạng thái dữ liệu",
    product: "Sản phẩm",
    channel: "Kênh bán hàng",
    created_by: "Người tạo",
    handler_assigned_date: "Ngày chia số",
    fail_reason: "Lý do không mua",
    fanpage: "Fanpage",
    handle_by: "Người xử lý",
    handle_reason: "Lý do xử lý",
    handle_status: "Trạng thái xử lý",
    bad_data_reason: "Dữ liệu không chất lượng",
    ad_channel: "Kênh",
    ad_account: "Người chạy",
    ad_id_content: "Id content",
    ad_campaign_type: "Loại chiến dịch",
    ad_partner: "Đại lý",
    ad_product_code: "Mã sản phẩm",
  },
  sum: "Tổng",
  count: "Tổng",
  closed: "Đã đóng",
  unclosed: "Không đóng",
  cancelled: "Đã hủy",
  uncancelled: "Không hủy",
  confirmed: "Đã xác nhận",
  unconfirmed: "Không xác nhận",
  open_id: "Tài khoản Google",
  restricted: "Không có quyền",
  helper_text: {
    please_enter_the_correct_phone_number: "Vui lòng nhập đúng số điện thoại",
    please_enter_customer_name: "Vui lòng nhập tên",
    please_select_source_name: "Vui lòng chọn kênh bán hàng",
    please_select_product: "Vui lòng chọn sản phẩm",
  },
  actions: {
    delete: "Xóa",
    create: "Tạo",
    update: "Cập nhật",
  },
  history: "Lịch sử",
  phone_existed: "SĐT trùng",
  ip_existed: "IP trùng",
  scheduler: {},
  kanban: {
    add_column: "Thêm cột",
    add_data: "Thêm dữ liệu",
    rename_column: "Đổi tên cột",
    delete_column: "Xóa cột",
    handle: "Xử lý",
    lateDelivery: "Đơn giao chậm",
    wfd: "Đơn chờ giao lại",
    returning: "Đơn hoàn",
    reportHandleStatus: "Báo cáo xử lý",
    order_late_delivery: "Đơn giao chậm",
    order_returning_and_returned: "Đơn hoàn",
    order_wait_for_delivery: "Đơn chờ giao lại",
  },
  success: "Thành công",
  error: "Thất bại",
  received: "Đã nhận",
  shipping: {
    tracking_number: "Mã vận đơn",
    to_name: "Tên khách hàng",
  },
  phone: "Số điện thoại",
  "Cannot update product status to inactive while one of its variants is active":
    "Không thể cập nhật trạng thái sản phẩm ngừng kinh doanh khi một trong biến thể đang kinh doanh",
};
