import { Column, TableColumnWidthInfo } from "@devexpress/dx-react-grid";
import { ColumnShow, ColumnShowDatagrid } from "_types_/FacebookType";
import { OrderPaymentTypeV2 } from "_types_/OrderType";
import { ReportOrderType } from "_types_/ReportOrderType";

export const columnWidthsDefault = [
  { width: 200, columnName: "info" },
  { width: 200, columnName: "customer" },
  { width: 200, columnName: "product" },
  { width: 300, columnName: "order" },
  { width: 200, columnName: "shipping" },
  { width: 200, columnName: "cost" },
  { width: 200, columnName: "payment" },
  { width: 200, columnName: "status" },
];

export const columnShowReportOrder: ColumnShowDatagrid<ReportOrderType> = {
  columnWidths: columnWidthsDefault,
  columnsShowHeader: [
    { name: "customer", title: "Khách hàng", isShow: true },
    { name: "info", title: "Thông tin", isShow: true },
    { name: "status", title: "Trạng thái", isShow: true },
    { name: "order", title: "Đơn hàng", isShow: true },
    { name: "cost", title: "Phí", isShow: true },
    { name: "shipping", title: "Vận chuyển", isShow: true },
    { name: "payment", title: "Thanh toán", isShow: true },
  ],
  columnShowTable: [
    { name: "status", title: "Trạng thái", column: "info", isShow: true, isShowTitle: false },
    { name: "order_key", title: "Mã đơn hàng", column: "info", isShow: true },
    { name: "created", title: "Ngày tạo", column: "info", isShow: true },
    { name: "completed_time", title: "Ngày xác nhận", column: "info", isShow: true },
    { name: "created_by__name", title: "Người tạo", column: "info", isShow: true },
    { name: "modified_by__name", title: "Người xử lí", column: "info", isShow: true },
    {
      name: "customer_phone",
      title: "SDT khách hàng",
      column: "customer",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "customer_name",
      title: "Tên khách hàng",
      column: "customer",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "is_printed",
      title: "Trạng thái in",
      column: "status",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "imported",
      title: "Trạng thái nhập kho",
      column: "status",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "exported",
      title: "Trạng thái xuất kho",
      column: "status",
      isShow: true,
      isShowTitle: false,
    },
    { name: "printed_at", title: "Ngày in đơn", column: "order", isShow: true },
    { name: "printed_by__name", title: "Người in đơn", column: "order", isShow: true },
    { name: "source__name", title: "Kênh bán hàng", column: "order", isShow: true },
    { name: "total_variant_all", title: "Tiền hàng trước KM", column: "order", isShow: true },
    { name: "total_variant_actual", title: "Tiền hàng sau KM", column: "order", isShow: true },
    { name: "total_actual", title: "Tổng giá trị đơn hàng", column: "order", isShow: true },
    { name: "fee_delivery", title: "Phí ship", column: "cost", isShow: true },
    { name: "fee_additional", title: "Phụ thu", column: "cost", isShow: true },
    { name: "discount_promotion", title: "Khuyển mãi trên đơn", column: "cost", isShow: true },
    { name: "discount_input", title: "Giảm giá", column: "cost", isShow: true },
    { name: "promotions__name", title: "Mã khuyến mãi đơn hàng", column: "cost", isShow: true },
    { name: "payment_note", title: "Ghi chú thanh toán", column: "cost", isShow: true },
    { name: "note", title: "Ghi chú nội bộ", column: "cost", isShow: true },
    { name: "shipping__created", title: "Ngày tạo vận đơn", column: "shipping", isShow: true },
    { name: "shipping__tracking_number", title: "Mã vận đơn", column: "shipping", isShow: true },
    { name: "shipping__note", title: "Ghi chú vận đơn", column: "shipping", isShow: true },
    { name: "shipping_address", title: "Địa chỉ nhận hàng", column: "shipping", isShow: true },
    {
      name: "shipping__return_full_address",
      title: "Địa chỉ kho giao hàng",
      column: "shipping",
      isShow: true,
    },
    { name: "shipping__return_name", title: "Kho bán", column: "shipping", isShow: true },
    { name: "payment_cod", title: "COD", column: "payment", isShow: true },
    { name: "payment_cash", title: "Thanh toán trực tiếp", column: "payment", isShow: true },
    { name: "payment_direct_transfer", title: "Chuyển khoản", column: "payment", isShow: true },
  ],
};

export const columnShowReportOrderItem: ColumnShowDatagrid<ReportOrderType> = {
  columnWidths: [
    { width: 150, columnName: "order_key" },
    { width: 150, columnName: "created" },
    { width: 170, columnName: "created_by__name" },
    { width: 130, columnName: "status" },
    { width: 170, columnName: "completed_time" },
    { width: 170, columnName: "modified_by__name" },
    { width: 120, columnName: "is_printed" },
    { width: 170, columnName: "printed_at" },
    { width: 170, columnName: "printed_by__name" },
    { width: 170, columnName: "source__name" },
    { width: 170, columnName: "tags__name" },
    { width: 130, columnName: "fee_delivery" },
    { width: 130, columnName: "fee_additional" },
    { width: 130, columnName: "discount_promotion" },
    { width: 130, columnName: "discount_input" },
    { width: 170, columnName: "promotions__name" },
    { width: 170, columnName: "payment_note" },
    { width: 170, columnName: "note" },
    { width: 170, columnName: "total_variant_all" },
    { width: 170, columnName: "total_variant_actual" },
    { width: 170, columnName: "total_actual" },
    { width: 170, columnName: "payment_cod" },
    { width: 170, columnName: "payment_cash" },
    { width: 170, columnName: "payment_direct_transfer" },
    { width: 170, columnName: "shipping__created" },
    { width: 170, columnName: "shipping__tracking_number" },
    { width: 170, columnName: "shipping__delivery_company_name" },
    { width: 170, columnName: "shipping__note" },
    { width: 170, columnName: "shipping_address" },
    { width: 170, columnName: "shipping__return_name" },
    { width: 170, columnName: "shipping__return_full_address" },
    { width: 170, columnName: "line_items__variant__SKU_code" },
    { width: 170, columnName: "line_items__variant__name" },
    { width: 130, columnName: "line_items__quantity" },
    { width: 130, columnName: "is_gift" },
    { width: 170, columnName: "line_items__promotion__name" },
    { width: 170, columnName: "line_items__total" },
    { width: 170, columnName: "line_items__variant_total" },
    { width: 170, columnName: "customer_name" },
    { width: 170, columnName: "customer_phone" },
    { width: 130, columnName: "exported" },
    { width: 130, columnName: "imported" },
    { width: 170, columnName: "exported_date" },
    { width: 170, columnName: "imported_date" },
    { width: 170, columnName: "shipping__modified" },
    { width: 170, columnName: "shipping__carrier_status" },
    { width: 170, columnName: "ecommerce_code" },
    // { width: 170, columnName: "payment_cod_date" },
    { width: 170, columnName: "payment_cod_confirm_date" },
    { width: 170, columnName: "payment_cash_date" },
    { width: 170, columnName: "payment_direct_transfer_date" },
  ],
  columnsShowHeader: [
    { name: "order_key", title: "Mã đơn hàng", isShow: true },
    { name: "created", title: "Ngày tạo", isShow: true },
    { name: "created_by__name", title: "Người tạo", isShow: true },

    { name: "status", title: "Trạng thái đơn", isShow: true },
    { name: "completed_time", title: "Ngày xác nhận", isShow: true },
    { name: "modified_by__name", title: "Người xử lý", isShow: true },
    { name: "is_printed", title: "Đã in đơn", isShow: true },
    { name: "printed_at", title: "Ngày in đơn", isShow: true },
    { name: "printed_by__name", title: "Người in đơn", isShow: true },
    { name: "source__name", title: "Kênh bán hàng", isShow: true },
    { name: "tags__name", title: "Thẻ đơn", isShow: true },
    { name: "customer_name", title: "Khách hàng", isShow: true },
    { name: "customer_phone", title: "SĐT Khách hàng", isShow: true },
    { name: "exported", title: "Xuất kho", isShow: true },
    { name: "imported", title: "Nhập kho", isShow: true },

    { name: "fee_delivery", title: "Phí ship", isShow: true },
    { name: "fee_additional", title: "Phụ thu", isShow: true },
    { name: "discount_promotion", title: "Khuyển mãi trên đơn", isShow: true },
    { name: "discount_input", title: "Giảm giá", isShow: true },
    { name: "promotions__name", title: "Mã khuyến mãi đơn hàng", isShow: true },
    { name: "payment_note", title: "Ghi chú thanh toán", isShow: true },
    { name: "note", title: "Ghi chú nội bộ", isShow: true },

    { name: "total_variant_all", title: "Tiền hàng trước KM", isShow: true },
    { name: "total_variant_actual", title: "Tiền hàng sau KM", isShow: true },
    { name: "total_actual", title: "Tổng giá trị đơn hàng", isShow: true },

    { name: "payment_cod", title: "COD", isShow: true },
    { name: "payment_cash", title: "Thanh toán trực tiếp", isShow: true },
    { name: "payment_direct_transfer", title: "Chuyển khoản", isShow: true },

    { name: "shipping__created", title: "Ngày tạo vận đơn", isShow: true },
    { name: "shipping__tracking_number", title: "Mã vận đơn", isShow: true },
    { name: "shipping__delivery_company_name", title: "Đơn vị vận chuyển", isShow: true },
    { name: "shipping__note", title: "Ghi chú vận đơn", isShow: true },
    { name: "shipping_address", title: "Địa chỉ nhận hàng", isShow: true },
    { name: "shipping__return_full_address", title: "Địa chỉ kho giao hàng", isShow: true },
    { name: "shipping__return_name", title: "Kho bán", isShow: true },

    { name: "line_items__variant__SKU_code", title: "SKU", isShow: true },
    { name: "line_items__variant__name", title: "Tên sản phẩm", isShow: true },
    { name: "line_items__quantity", title: "Số Lượng", isShow: true },
    { name: "is_gift", title: "Hàng khuyến mãi", isShow: true },
    { name: "line_items__promotion__name", title: "Mã khuyến mãi SKU", isShow: true },
    { name: "line_items__total", title: "Giá khuyến mãi", isShow: true },
    { name: "line_items__variant_total", title: "Giá bán", isShow: true },
    { name: "exported_date", title: "Ngày xuất kho", isShow: true },
    { name: "imported_date", title: "Ngày nhập kho (hoàn hàng)", isShow: true },
    { name: "shipping__carrier_status", title: "Trạng thái vận đơn hiện tại", isShow: true },
    { name: "shipping__modified", title: "Ngày cập nhật trạng thái vận đơn", isShow: true },
    { name: "ecommerce_code", title: "Mã TMĐT", isShow: true },
    // { name: "payment_cod_date", title: "Ngày chuyển COD", isShow: false },
    { name: "payment_cod_confirm_date", title: "Ngày xác thực thanh toán COD", isShow: true },
    { name: "payment_cash_date", title: "Ngày xác thực thanh toán trực tiếp", isShow: true },
    {
      name: "payment_direct_transfer_date",
      title: "Ngày xác thực thanh toán chuyển khoản",
      isShow: true,
    },
  ],
  columnShowTable: [
    {
      name: "order_key",
      column: "order_key",
      title: "Mã đơn hàng",
      isShow: true,
      isShowTitle: false,
    },
    { name: "created", column: "created", title: "Ngày tạo", isShow: true, isShowTitle: false },
    {
      name: "created_by__name",
      column: "created_by__name",
      title: "Người tạo",
      isShow: true,
      isShowTitle: false,
    },

    { name: "status", column: "status", title: "Trạng thái đơn", isShow: true, isShowTitle: false },
    {
      name: "completed_time",
      column: "completed_time",
      title: "Ngày xác nhận",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "modified_by__name",
      column: "modified_by__name",
      title: "Người xử lý",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "is_printed",
      column: "is_printed",
      title: "Đã in đơn",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "printed_at",
      column: "printed_at",
      title: "Ngày in đơn",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "printed_by__name",
      column: "printed_by__name",
      title: "Người in đơn",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "source__name",
      column: "source__name",
      title: "Kênh bán hàng",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "tags__name",
      column: "tags__name",
      title: "Thẻ đơn",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "customer_name",
      column: "customer_name",
      title: "Khách hàng",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "customer_phone",
      column: "customer_phone",
      title: "SĐT Khách hàng",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "exported",
      column: "exported",
      title: "Xuất kho",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "imported",
      column: "imported",
      title: "Nhập kho",
      isShow: true,
      isShowTitle: false,
    },

    {
      name: "fee_delivery",
      column: "fee_delivery",
      title: "Phí ship",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "fee_additional",
      column: "fee_additional",
      title: "Phụ thu",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "discount_promotion",
      column: "discount_promotion",
      title: "Khuyển mãi trên đơn",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "discount_input",
      column: "discount_input",
      title: "Giảm giá",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "promotions__name",
      column: "promotions__name",
      title: "Mã khuyến mãi đơn hàng",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "payment_note",
      column: "payment_note",
      title: "Ghi chú thanh toán",
      isShow: true,
      isShowTitle: false,
    },
    { name: "note", column: "note", title: "Ghi chú nội bộ", isShow: true, isShowTitle: false },

    {
      name: "total_variant_all",
      column: "total_variant_all",
      title: "Tiền hàng trước KM",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "total_variant_actual",
      column: "total_variant_actual",
      title: "Tiền hàng sau KM",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "total_actual",
      column: "total_actual",
      title: "Tổng giá trị đơn hàng",
      isShow: true,
      isShowTitle: false,
    },

    { name: "payment_cod", column: "payment_cod", title: "COD", isShow: true, isShowTitle: false },
    {
      name: "payment_cash",
      column: "payment_cash",
      title: "Thanh toán trực tiếp",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "payment_direct_transfer",
      column: "payment_direct_transfer",
      title: "Chuyển khoản",
      isShow: true,
      isShowTitle: false,
    },

    {
      name: "shipping__created",
      column: "shipping__created",
      title: "Ngày tạo vận đơn",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "shipping__tracking_number",
      column: "shipping__tracking_number",
      title: "Mã vận đơn",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "shipping__delivery_company_name",
      column: "shipping__delivery_company_name",
      title: "Đơn vị vận chuyển",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "shipping__note",
      column: "shipping__note",
      title: "Ghi chú vận đơn",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "shipping_address",
      column: "shipping_address",
      title: "Địa chỉ nhận hàng",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "shipping__return_full_address",
      column: "shipping__return_full_address",
      title: "Địa chỉ kho giao hàng",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "shipping__return_name",
      column: "shipping__return_name",
      title: "Kho bán",
      isShow: true,
      isShowTitle: false,
    },

    {
      name: "line_items__variant__SKU_code",
      column: "line_items__variant__SKU_code",
      title: "SKU",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "line_items__variant__name",
      column: "line_items__variant__name",
      title: "Tên sản phẩm",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "line_items__quantity",
      column: "line_items__quantity",
      title: "Số Lượng",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "is_gift",
      column: "is_gift",
      title: "Hàng khuyến mãi",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "line_items__promotion__name",
      column: "line_items__promotion__name",
      title: "Mã khuyến mãi SKU",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "line_items__total",
      column: "line_items__total",
      title: "Giá khuyến mãi",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "line_items__variant_total",
      column: "line_items__variant_total",
      title: "Giá bán",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "exported_date",
      column: "exported_date",
      title: "Ngày xuất kho",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "imported_date",
      column: "imported_date",
      title: "Ngày nhập kho (hoàn hàng)",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "shipping__carrier_status",
      column: "shipping__carrier_status",
      title: "Trạng thái vận đơn hiện tại",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "shipping__modified",
      column: "shipping__modified",
      title: "Ngày cập nhật trạng thái vận đơn",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "ecommerce_code",
      column: "ecommerce_code",
      title: "Mã TMĐT",
      isShow: true,
      isShowTitle: false,
    },
    // { name: "payment_cod_date",column: e: "payment_cod_date", title: "Ngày chuyển COD", isShow: false  ,isShowTitle: false},
    {
      name: "payment_cod_confirm_date",
      column: "payment_cod_confirm_date",
      title: "Ngày xác thực thanh toán COD",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "payment_cash_date",
      column: "payment_cash_date",
      title: "Ngày xác thực thanh toán trực tiếp",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "payment_direct_transfer_date",
      column: "payment_direct_transfer_date",
      title: "Ngày xác thực thanh toán chuyển khoản",
      isShow: true,
      isShowTitle: false,
    },
  ],
};

export const columnShowReportOrderKpi: ColumnShowDatagrid<ReportOrderType> = {
  columnWidths: columnWidthsDefault,
  columnsShowHeader: [
    { name: "customer", title: "Khách hàng", isShow: true },
    { name: "info", title: "Thông tin", isShow: true },
    { name: "order", title: "Đơn hàng", isShow: true },
    { name: "cost", title: "Phí", isShow: true },
    { name: "shipping", title: "Vận chuyển", isShow: true },
  ],
  columnShowTable: [
    { name: "order_key", title: "Mã đơn hàng", column: "info", isShow: true },
    { name: "completed_time", title: "Ngày xác nhận", column: "info", isShow: true },
    { name: "created_by__name", title: "Người tạo", column: "info", isShow: true },
    {
      name: "customer_phone",
      title: "SDT khách hàng",
      column: "customer",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "customer_name",
      title: "Tên khách hàng",
      column: "customer",
      isShow: true,
      isShowTitle: false,
    },
    { name: "source__name", title: "Kênh bán hàng", column: "order", isShow: true },
    // { name: "tags__name", title: "Thẻ", column: "order", isShow: true },
    { name: "total_actual", title: "Tổng giá trị đơn hàng", column: "order", isShow: true },

    { name: "fee_delivery", title: "Phí ship", column: "cost", isShow: true },
    { name: "fee_additional", title: "Phụ thu", column: "cost", isShow: true },
    {
      name: "shipping__delivery_company_name",
      title: "Đơn vị vận chuyển",
      column: "shipping",
      isShow: true,
      isShowTitle: false,
    },
    {
      name: "shipping__carrier_status",
      title: "Trạng thái vận đơn",
      column: "shipping",
      isShow: true,
    },
    { name: "shipping__finish_date", title: "Ngày hoàn thành", column: "shipping", isShow: true },
  ],
};

// Summary
export const valueGetParamsDefault = [
  "created_from",
  "created_to",
  "completed_time_from",
  "completed_time_to",
  "shipping_finished_from",
  "shipping_finished_to",
  "source",
  "delivery_company",
  "status",
  "created_by",
  "tags",
  "is_printed",
  "is_cross_sale",
  "payment_type",
  "search",
  "carrier_status",
];

export const IMPORT_PAYMENT_COLUMNS: Column[] = [
  { title: "Stt", name: "rowId" },
  { name: "OrderKey", title: "Mã đơn" },
  { name: "Amount", title: "Số tiền nhận" },
  { name: "ReceivedDate", title: "Ngày nhận" },
  { name: "ShippingUnit", title: "Đơn vị vận chuyển" },
  { name: "PaymentMethod", title: "Phương thức thanh toán" },
  { name: "TransactionCode", title: "Mã thanh toán" },
  { name: "Images", title: "Hình ảnh" },
];

export const IMPORT_PAYMENT_COLUMN_WIDTHS: TableColumnWidthInfo[] = [
  { columnName: "rowId", width: 65 },
  { columnName: "OrderKey", width: 100 },
  { columnName: "Amount", width: 130 },
  { columnName: "ReceivedDate", width: 140 },
  { columnName: "ShippingUnit", width: 170 },
  { columnName: "PaymentMethod", width: 180 },
  { columnName: "TransactionCode", width: 150 },
  { columnName: "Images", width: 200 },
];

export const COLLATION_PAYMENT_COLUMNS: ColumnShow<OrderPaymentTypeV2> = {
  columnsShowHeader: [
    { name: "type", title: "Loại thanh toán", isShow: false },
    { name: "amount", title: "Số tiền", isShow: false },
    { name: "confirmed_date", title: "Trạng thái xác nhận", isShow: false },
    { name: "third_party_paid_status", title: "TT 3rd", isShow: false },
    { name: "internal_paid_status", title: "TT nội bộ", isShow: false },
    { name: "final_paid_status", title: "Trạng thái TT", isShow: false },
    { name: "is_confirmed", title: "Đã xác nhận", isShow: false },
    { name: "receive_info", title: "Thực nhận", isShow: false },
    //
    { name: "upload_info", title: "Up File", isShow: true },
    { name: "order_info", title: "Đơn hàng", isShow: true }, //
    { name: "collation_info", title: "Đối soát", isShow: true }, //
    { name: "images", title: "Hình ảnh", isShow: true },
  ],
  columnWidths: [
    { columnName: "type", width: 150 },
    { columnName: "amount", width: 100 },
    { columnName: "confirmed_date", width: 200 },
    { columnName: "third_party_paid_status", width: 130 },
    { columnName: "internal_paid_status", width: 130 },
    { columnName: "final_paid_status", width: 130 },
    { columnName: "is_confirmed", width: 130 },
    { columnName: "receive_info", width: 300 },
    //
    { columnName: "upload_info", width: 230 },
    { columnName: "order_info", width: 250 },
    { columnName: "collation_info", width: 250 },
    { columnName: "images", width: 250 },
  ],
};

export const COLLATION_SORT_FIELDS: { [key: string]: string } = {
  amount: "Số tiền",
  actual_amount: "Số tiền thực nhận",
  upload_at: "Thời gian up file",
  confirmed_date: "Thời gian xác nhận",
  order_key: "Mã đơn hàng",
};
