apiVersion: v1
kind: Service
metadata:
  name: crm-frontend-svc-nodeport
  namespace: crm
spec:
  type: NodePort
  selector:
    app: crm-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30300
