apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-issuer
  namespace: develop
spec:
  acme:
    email: thuong.nh@skylinktech.vn
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key
    solvers:
      # Use the HTTP-01 challenge provider
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-nginx-front-end-dev
  namespace: develop
spec:
  secretName: letsencrypt-nginx-front-end-dev
  dnsNames:
    - dev.skycom.vn
  issuerRef:
    group: cert-manager.io
    name: cert-manager-issuer
    kind: Issuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-public-front-end
  namespace: develop
  annotations:
    # SSl 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dev.skycom.vn
    secretName: letsencrypt-nginx-front-end-dev
  rules:
  - host: dev.skycom.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end-web-service
            port:
              number: 80
## chỉ chạy lần đầu và thay đổi host cho từng tenant line 41 (p/s: gắn ip domain tới loadbanlencer)