apiVersion: v1
kind: Namespace
metadata:
  name: front-end
  labels:
    name: front-end
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-pull-secret
  namespace: front-end
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <GITLAB_PULL_SECRET>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-web-deployment
  namespace: front-end
  labels:
    app: front-end-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: front-end-web-pod
  template:
    metadata:
      labels:
        app: front-end-web-pod
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: front-end-web
        image: front-end-k8s:test1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 400Mi
          limits:
            cpu: 200m
            memory: 400Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: front-end-web-service
  namespace: front-end
spec:
  selector:
    app: front-end-web-pod
  type: ClusterIP
  ports:
  - name: defaut-port
    protocol: TCP
    port: 80
    targetPort: 80
---
