#!/bin/sh
#ecommerce
echo CI_JOB_TOKEN=$CI_JOB_TOKEN  >> .env.prod
echo CI_REGISTRY_USER=$CI_REGISTRY_USER   >> .env.prod
echo CI_REGISTRY=$CI_REGISTRY  >> .env.prod
echo DEBUG=0 >> .env.prod
echo IMAGE=$IMAGE >> .env.prod
echo NGINX_IMAGE=$IMAGE:nginx  >> .env.prod
echo REACT_APP_API_URL=$REACT_APP_API_URL_PROD >> .env.prod
echo REACT_APP_CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA >> .env.prod
echo REACT_APP_CI_COMMIT_TIMESTAMP=$CI_COMMIT_TIMESTAMP >> .env.prod
echo REACT_APP_DIGITAL_OCEAN_IP_ADDRESS=$REACT_APP_DIGITAL_OCEAN_IP_ADDRESS  >> .env.prod
echo REACT_APP_FACEBOOK_DEV_ID=$REACT_APP_FACEBOOK_DEV_ID_PROD >> .env.prod
echo REACT_APP_GHN_API_URL=$REACT_APP_GHN_API_URL  >> .env.prod
echo REACT_APP_GHN_FE_ONLINE_API_URL=$REACT_APP_GHN_FE_ONLINE_API_URL_PROD  >> .env.prod
echo REACT_APP_GHN_SHOP_ID_DEV=$REACT_APP_GHN_SHOP_ID_DEV_PROD  >> .env.prod
echo REACT_APP_GHN_SHOP_ID=$REACT_APP_GHN_SHOP_ID_PROD  >> .env.prod
echo REACT_APP_GHN_TOKEN_DEV=$REACT_APP_GHN_TOKEN_DEV_PROD  >> .env.prod
echo REACT_APP_GHN_TOKEN=$REACT_APP_GHN_TOKEN_PROD  >> .env.prod
echo REACT_APP_HOTLINE=$REACT_APP_HOTLINE  >> .env.prod
echo REACT_APP_NGINX_IMAGE=$IMAGE:nginx  >> .env.prod
echo REACT_APP_ORGANIZATION_ID=$REACT_APP_ORGANIZATION_ID_PROD  >> .env.prod
echo REACT_APP_PRIVACY_URL=$REACT_APP_PRIVACY_URL_PROD >> .env.prod
echo REACT_APP_REPORT_API=$REACT_APP_API_REPORT_PROD  >> .env.prod
echo REACT_APP_SENTRY_URL=$REACT_APP_SENTRY_URL_PROD >> .env.prod
echo REACT_APP_SHOP_ADDRESS=$REACT_APP_SHOP_ADDRESS  >> .env.prod
echo REACT_APP_SHOP_NAME_2=$REACT_APP_SHOP_NAME_2  >> .env.prod
echo REACT_APP_SHOP_NAME=$REACT_APP_SHOP_NAME  >> .env.prod
echo REACT_APP_SHOPEE_SHOP_ID=$REACT_APP_SHOPEE_SHOP_ID_PROD >> .env.prod
echo REACT_APP_SKYCOM_API=$REACT_APP_SKYCOM_API_PROD  >> .env.prod
echo REACT_APP_URL_DATA=$REACT_APP_API_URL_DATA_PROD >> .env.prod
# call center
echo REACT_APP_CALL_CENTER_API=$REACT_APP_CALL_CENTER_API_PROD  >> .env.prod
# spam checking
echo REACT_APP_API_SYNC_DATA=$REACT_APP_API_SYNC_DATA_PROD >> .env.prod